version: "3.9"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=timetabling
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=dbpassword
    ports:
      - "3302:3306"
    networks:
      - db-net
    volumes:
      - dbvolume:/var/lib/mysql

  mq:
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: "RABBITMQ_ERLANG_COOKIE"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
   
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - mqvolume:/var/lib/rabbitmq/
    networks:
      - mq-net

  mqworker:
    build: ./queue
    command: ["python", "worker.py"]
    restart: on-failure
    depends_on:
      - mq
      - backend
    networks:
      - mq-net

  backend:
    build: ./backend
    hostname: backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
     - db
     - mq
    networks:
     - db-net
     - mq-net
     
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
  
networks:
  db-net:
    driver: bridge
  mq-net:
    driver: bridge

volumes:
  dbvolume:
  mqvolume: