version: "3.9"

services:
  db:
    image: mysql:8.0.23
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=bug
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=dbadmin
    ports:
      - "3302:3306"
    networks:
      - db-net

  backend:
    build: ./backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
     - db
    networks:
     - db-net
     
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
  
networks:
  db-net:
    driver: bridge
