# Generated by Django 3.2 on 2021-05-05 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this timetable task', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('publication_date', models.DateTimeField()),
                ('computation_finish_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('r', 'Running'), ('f', 'Finished')], default='w', help_text='Timetable processing status', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
