# Generated by Django 3.2 on 2021-05-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='input',
            field=models.CharField(default='asd', help_text='Traveling Salesman Problem data input', max_length=32767),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='output',
            field=models.CharField(default='a', max_length=511),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('r', 'Running'), ('f', 'Finished')], default='w', help_text='Task processing status', max_length=1),
        ),
    ]
