# Generated by Django 3.2 on 2021-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
